### ISSUE TITLE
Build image for ARM

### ISSUE THREAD

**Issue by notdodo** [kpeiruza/docker-hashtopolis-server#3]
Hi!

Can you build and update the docker hub image for ARM devices (odroid, raspberry, etc)?
Right now the image on dockerhub can be used only on x86 arch

EDIT: Thank you for the work :)

**Comment by kpeiruza** [comment]
Hi
Thank you for being interested in the project.

I've never built images for ARM devices, and I've just checked that it can be done with a special image in the FROM.

That would allow us to keep the image as an Automated Build, so everyone can trace&trust the steps executed during the build process.

In the meantime, can you please verify if the build process works on ARM? If you still need the image to be an automated build available from hub.docker.com, I'd build a specific Dockerfile & tag for ARM if you still need it and I'll be glad to have you as ARM tester :-)

Thanks!

**Comment by notdodo** [comment]
Thank you for the response!

I'll check if I can build the image from scratch on ARM.
I can help you managing ARM images but I got only a armv7 device (Odroid C2); if it helps I'm glad to help.

**Comment by notdodo** [comment]
Just a quick heads-up: `mysql` image is not available on ARM as well.
I'll try to switch to mariadb

**Comment by notdodo** [comment]
Hi!

![Screenshot_20200513_205309](https://user-images.githubusercontent.com/6991986/81852758-d10bde80-955b-11ea-828b-546fbd5cf88a.png)

I've managed to get it run using Mariadb and this commands:

```
git clone https://github.com/kpeiruza/docker-hashtopolis-server.git
cd docker-hashtopolis-server
docker build --force-rm . -t notdodo:hashtopolis
sudo docker run --name mysql -e MYSQL_ROOT_PASSWORD=test -d mariadb
docker run -e H8_USER=notdodo -e H8_PASS=test --link mysql:mysql -d -p 8080:80 notdodo:hashtopolis
```

I needed to rebuild your hashtopolis image and link it to mariadb.

**Comment by notdodo** [comment]
@kpeiruza do you mind sharing your automated build config and process?

**Comment by kpeiruza** [comment]
Hi!

There's no extra magic, just the files in this repo and create a default-next-next-next automated build on https://hub.docker.com ...

In your case, you'll need to add a build image for cross-platform as shown here:

https://medium.com/@kurt.stam/building-aarch64-arm-containers-on-dockerhub-d2d7c975215c

Regards!
