### ISSUE TITLE
PHP Errors any time php?id=xx is used. Browser shows error 500

### ISSUE THREAD

**Issue by sondercoder** [kpeiruza/docker-hashtopolis-server#4]
System:

Ubuntu 20.04.1 LTS
docker-compose version 1.25.0, build unknown
Docker version 19.03.8, build afacb8b7f0
added an nginx proxy config to wrap it in ssl for remote agents - behavior is the same using this or not, both ports are exposed locally.

Either a system update broke this, or the updated image, and I just didnt notice.

docker-compose.yaml
version: '3.7'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: anotherpw
    restart: unless-stopped
  hashtopolis:
    image: kpeiruza/hashtopolis:latest
    environment:
      H8_USER: root
      H8_PASS: somepw
      H8_EMAIL: root@localhost
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: anotherpw
      MYSQL_DB: hashtopolis
    volumes:
      - import:/var/www/html/import
      - files:/var/www/html/files
      - inc:/var/www/html/inc
      - locks:/var/www/html/inc/utils/locks
    ports:
      - "8008:80"
    restart: unless-stopped
  nginx:
    image: nginx:stable
    container_name: production_nginx
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf'
      - './nginx/certs/ca.crt:/etc/nginx/certs/ca.crt'
      - './nginx/certs/server.crt:/etc/nginx/certs/server.crt'
      - './nginx/certs/server.key:/etc/nginx/certs/server.key'
    ports:
      - 8334:8334
    restart: unless-stopped
volumes:
  import: {}
  files: {}
  inc: {}
  locks: {}
  mysql: {}

When clicking an actual agent in agent lists:
PHP Fatal error:  Uncaught Error: Undefined class constant 'CPU_UTIL' in /var/www/html/agents.php:91\nStack trace:\n#0 {main}\n  thrown in /var/www/html/agents.php on line 91, referer: http://127.0.0.1:8008/agents.php

When clicking a task that is part of a hashlist
PHP Fatal error:  Uncaught Error: Undefined class constant 'SET_STATUS_TIMER' in /var/www/html/inc/templating/Statement.class.php(190) : eval()'d code:1\nStack trace:\n#0 /var/www/html/inc/templating/Statement.class.php(190): eval()\n#1 /var/www/html/inc/templating/Statement.class.php(139): Statement->evalResult('$DTaskAction::S...', Array, false)\n#2 /var/www/html/inc/templating/Statement.class.php(92): Statement->renderVariable('[[$DTaskAction:...', Array, false)\n#3 /var/www/html/inc/templating/Statement.class.php(71): Statement->renderContent('\\n            <f...', Array)\n#4 /var/www/html/inc/templating/Statement.class.php(30): Statement->render(Array)\n#5 /var/www/html/inc/templating/Template.class.php(53): Statement->render(Array)\n#6 /var/www/html/tasks.php(427): Template->render(Array)\n#7 {main}\n  thrown in /var/www/html/inc/templating/Statement.class.php(190) : eval()'d code on line 1, referer: https://127.0.0.1:8334/hashlists.php?id=2

**Comment by sondercoder** [comment]
Just to test, I built a new env on the same server, and I can't even register a new agent:

Registering failed: {'action': 'register', 'response': 'ERROR', 'message': 'Provided voucher does not exist.'}
No token found! Please enter a voucher to register your agent:
xxxxxxxxx
Status code from server: 500
Request failed!
No token found! Please enter a voucher to register your agent:
xxxxxxxxx
Registering failed: {'action': 'register', 'response': 'ERROR', 'message': 'Provided voucher does not exist.'}
No token found! Please enter a voucher to register your agent:

**Comment by sondercoder** [comment]
Didnt mean to close thread.

**Comment by sondercoder** [comment]
So I created two VMs, both fresh installs of Ubuntu 18LTS and 20LTS, and fresh installs of docker/compose - and neither has the issue I am seeing.   Is there an issue upgrading the images and the db?  My original docker install was at pre-july this year.

**Comment by kpeiruza** [comment]
Hi @sondercoder,

The Docker image doesn't perform any upgrade tasks on DB. I guess this is why it failed. I'm not sure how it should be handled.

1) If there's code under /var/www/html , avoid copying it. This way you should be able to upgrade manually
2) time-consuming task to automate upgrade from version X to version Y.

As this project is something I've done in my free time and I'm not using it extensively, I'd go for #1, so, at least a new docker image will not render your current environment useless as far as there are no PHP compatibility issues.

Does this make sense to you? Feel free to mail me at kenneth at floss  . cat

Thank you for your feedback.

Kenneth
