### ISSUE TITLE
Docker crashes when rebooted

### ISSUE THREAD

**Issue by Metroseksuaali** [kpeiruza/docker-hashtopolis-server#5]
Hey, 

I might be bit noob in docker world and that might be problem number1.

But me and my friend have successfully installed docker for first time and everything is working fine until we reboot server and start container again. It will only loop and generate error that database with name Hashtopolis is already created and cannot be created again. After that container crashes.

How do we can edit container so it does not try to create new DB after rebooting?

**Comment by Metroseksuaali** [comment]
```
ERROR 1007 (HY000) at line 1: Can't create database 'Hashtopolis'; database exists

ERROR 1050 (42S01) at line 11: Table 'AccessGroup' already exists
```

**Comment by Gitoffomalawn** [comment]
The MySQL image used had lots of issues with DB initialization, which may have resulted in your issues. 

The `docker-compose.yaml` file has been updated to use MariaDB instead of MySQL, which should have solved all these issues. Try again using the new file, you shouldn't have any issues.
